Build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - echo $CI_ENV >> build/.env    
    - ls -la 
    - ls -la build    
  script:
    - chmod +x script_staging.sh script_master.sh
    - if [ "$CI_COMMIT_BRANCH" == "master" ]; then ./script_master.sh ; else ./script_staging.sh ; fi    

