Build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - imagen_docker="$CI_REGISTRY_IMAGE":"$CI_COMMIT_BRANCH"-"$CI_COMMIT_SHORT_SHA"  
    - echo $imagen_docker  
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"

# URL    
    - url="URL_""$CI_PROJECT_NAME""_""$CI_COMMIT_BRANCH" ;
    - echo $url;  
    - url=$(eval echo $(echo '$'$url)) ;
    - echo $url;   

#Construccion ENV

    - echo 'API_URL= "$url"' >> build/.env

  # SELECT master or staging ENV
    - echo "before_script - SELECT master or staging ENV" ;
    - if [ "$CI_COMMIT_BRANCH" == "master" ]; then 
        echo "MASTER" ; 
        cat "$CI_ENV_MASTER" > build/.env ;            
      else 
        echo "STAGING" ;
        cat "$CI_ENV_STAGING" > build/.env ;        
      fi

#    - ls -la 
#    - ls -la build    
    - cat build/.env 

  script:
    echo "CORRECTO" ;
