Build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - echo $CI_ENV >> build/.env    
    - ls -la 
    - ls -la build    
  script:
#    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
#    - docker tag  "$CI_REGISTRY_IMAGE" "$CI_REGISTRY_IMAGE":"$CI_COMMIT_BRANCH"-"$CI_COMMIT_SHORT_SHA"
#    - docker push "$CI_REGISTRY_IMAGE":"$CI_COMMIT_BRANCH"-"$CI_COMMIT_SHORT_SHA"
#    - docker tag  "$CI_REGISTRY_IMAGE" "$CI_REGISTRY_IMAGE":latest
#    - docker push "$CI_REGISTRY_IMAGE":latest    
    
#    - docker tag  "$CI_REGISTRY_IMAGE":"$CI_COMMIT_BRANCH"-"$CI_COMMIT_SHORT_SHA" "$CI_REGISTRY_IMAGE":latest
#    - docker push "$CI_REGISTRY_IMAGE":latest
#

    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker tag  "$CI_REGISTRY_IMAGE" "$CI_REGISTRY_IMAGE":"$CI_COMMIT_BRANCH"-"$CI_COMMIT_SHORT_SHA"
#    - docker push "$CI_REGISTRY_IMAGE":"$CI_COMMIT_BRANCH"-"$CI_COMMIT_SHORT_SHA"
    - docker tag  "$CI_REGISTRY_IMAGE" "$CI_REGISTRY_IMAGE":latest
    - docker push "$CI_REGISTRY_IMAGE"

 
