Build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - echo $CI_ENV >> build/.env    
    - ls -la 
    - ls -la build    
  script:
    - echo $CI_COMMIT_BRANCH
#    - export
#    - docker build --pull -t "$CI_REGISTRY_IMAGE":"$CI_COMMIT_BRANCH"-"$CI_COMMIT_SHORT_SHA" .
#    - docker push "$CI_REGISTRY_IMAGE"
