Build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - imagen_docker="$CI_REGISTRY_IMAGE":"$CI_COMMIT_BRANCH"-"$CI_COMMIT_SHORT_SHA"  
    - echo $imagen_docker  
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - echo 'API_URL= "https://stagingapiecm.autogermana.com.co"' >> build/.env
    - echo $CI_ENV_STAGING >> build/.env
#    - ls -la 
#    - ls -la build    
    - cat build/.env  
#    - chmod +x script_staging.sh script_master.sh
#

  script:
    echo "CORRECTO" ;

